### ISSUE TITLE
Update version with new releases

### ISSUE THREAD

**Issue by jasonbahl** [marketingg2/connext-wp-vip#4]
It would be fantastic if the version number was reflected when a new release is pushed. All releases show version 1.0.0 in the main plugin file.

**Comment by jasonbahl** [comment]
the package.json file also says the plugin is version 0.1.0. Would be good if that version number increased to reflect the version of each release as well.

**Comment by jaredcobb** [comment]
@jasonbahl Good catch, we have an upcoming release planned this month and I'll be sure to update the versions.
